### PR TITLE
maybe useful, maybe not: convert beginners-luck.cabal to hpack

### PR DESCRIPTION
**Pull request by hlian**
This takes advantage of stack's builtin support for [hpack](https://github.com/sol/hpack), a new package description language embedded in YAML. You may like this, you may not; I won't mind if you didn't merge it in. Compared to the Cabal format, hpack has two cool features:

* No more writing down all your modules into `exposed-modules`. hpack infers the modules by looking at your source code.

* No more copying and pasting the list of dependencies into each target. hpack allows a top-level dependencies list that each target then can inherit from.

### CODE REVIEW

**Comment by hlian** [comment]
@2016rshah @matthandlersux

**Comment by 2016rshah** [comment]
This seems cool, is there any additional setup instructions people getting started with the project would need? Or is it just something you run once or twice every so often and won't influence most contributors to the project? 

If it changes the getting started process we should add instructions on doing so to the README. This could be as simple as a section that just lists the commands to install hpack, run the tool, etc.

**Comment by hlian** [comment]
> This seems cool, is there any additional setup instructions people getting started with the project would need? Or is it just something you run once or twice every so often and won't influence most contributors to the project?

Nope! Works automatically with stack.

**Comment by 2016rshah** [comment]
Awesome, thanks!

**Pull request merged**
